**LIST**

- duplicate values allowed
- [ ]
- mutable and iterable (add, delete, modify, read) CRUD operations
- stores heterogeneous data
-lst= [10,12,13,5,7]
-lst= [10,12"xxx","yyy"]
-lst= [1,2,3,[100,200,300]]-> (list of 4)-> (lst[3][1]=200)
- we can perform all the perations on the inner list as that on the main list

*Append Function:
- add one value at the end of the list
- lst.append([100,200,300]) - creates a nested list

*Extend function:
- adds multiple values at a time at the end of the list
- lst.extend([100,200,300]) - makes 3 new elements

*Insert Function (pos , value)
- to insert a value in between  or anywhere in the list

*Pop Function;
- to delete the last value if position is not given, and a particular position if value is given.

*Remove Function
- to delete 1st occurance of an element from the list
- eg: lst2.remove(100)

*Count Function:
- to find number of occurances of the given value

*Clear Function:
- to remove all the elements from the list. keeps the empty list

*Index Function:
- to find the position of a given element

*Pos function:
- the value at the given position will be overwritten by the data

*Reverse Function:
- Reverses the given list


*Sort Function:
- In the list if all the values are of same type, then only sort is possible.
- It will sort in ascending order.
- For ascending-> lst.sort()
- For descending-> lst.sort(reverse=True)
- only possible on homogeneous data type
- if some value are float and some intgers it will work because they are numbers

*Copy Function:
- Creates a shallow copy of the list. It copies only references.
- lst1 = lst ; is a deep copy of the list lst ie lst1 points to the same memory location where lst is saved.

there is a copy module which has a deep copy function.
to create a complete deep copy

In [ ]:
lst=[] #empty list
lst=[10,20,30]
print("Length=", len(lst))

#to retrieve the value at given index
print(lst[2])
lst1= [10,12,"xxx","yyy"]
lst2= [1,2,3,"xxx",[100,200,300]]

#to get the value 200
print("to get the value from nestted list:" , lst2[3][1])

#to overwrite the value in d list
lst1[2]=20
print(lst1)

#add a value at the end
lst2.append("ssss")
print(lst2)

#extend
lst2.extend("abcd")
print(lst2)

lst2.insert(2, 50)
print(lst2)

print(lst2[5][2])

#Pop and Delete
#To delete all occurrances of 12
#n=12
lst3=[1,2,3,12,4,5,6,12,12,12]
print(lst3)
for i in lst3:
  if i == 12:
    lst3.remove(i)
    print(lst3)
  else:
    print("number not in list")

#print(lst3)

Length= 3
30
to get the value from nestted list: x
[10, 12, 20, 'yyy']
[1, 2, 3, 'xxx', [100, 200, 300], 'ssss']
[1, 2, 3, 'xxx', [100, 200, 300], 'ssss', 'a', 'b', 'c', 'd']
[1, 2, 50, 3, 'xxx', [100, 200, 300], 'ssss', 'a', 'b', 'c', 'd']
300
[1, 2, 3, 12, 4, 5, 6, 12, 12, 12]
number not in list
number not in list
number not in list
[1, 2, 3, 4, 5, 6, 12, 12, 12]
number not in list
number not in list
[1, 2, 3, 4, 5, 6, 12, 12]
[1, 2, 3, 4, 5, 6, 12]

**TUPLES**
- Allows to store multiple values.
- it is immutable and iterable
- ()
- allows to store duplicate values

*Count Function:
- to find number of occurances of the given value

*Index Function:
- to find the position of a given element

*Length
- gives length of tuple.

*Uses
- To return multiple value from a function
- To pass variable number of parameters to a function
- Allows to store duplicate values
- To send variable number of parameters to a function
- A function can return multiple values as a tuple

In [ ]:
a=12,13,13,"xxx"  #packing of tuple
a=(1,2,3,4)       #packing of tuple

'''
x = a[0]
y = a[1]
'''

x, y, z, p = a    #unpacking of tuple

a=12
b=23
b,a=a,b #Swapping in one line

#to create a tuple of size 1
a2 = 12,
a3 = (12,)
a4=tuple() #empty tuple can be created like this. But as it is immutable, it is of no use.


def add(x,y):
  x=x+10
  y=y+20
  print("Ïn function", x,y)
  return x+y,x,y    #packing of tuple

x=10
y=20

s,a,b=add(x,y)    #unpacking of tuple
print(add(x,y))
print(s,a,b)

def func1(a,b, *t):   #* is expanded version of tuple
  print(a,b)
  print(t)

func1(12,13)
func1(1,2,3,4,5,6,7,"a","b")

def findsum(a=23,b=10,*t):    #tuple can be empty - it is okay if default argument of tuple are not given even if others are given
  s=a+b
  for num in t:
    s=s+num
    print(s)
  return s
s=findsum(1,2,3,4,5,6,7)
print(f"Sum={s}")

#tuple is used to return multiple values from a function

Ïn function 20 40
Ïn function 20 40
(60, 20, 40)
60 20 40
12 13
()
1 2
(3, 4, 5, 6, 7, 'a', 'b')
6
10
15
21
28
Sum=28